-- ==========================================
-- 1. TABLES
-- ==========================================

create sequence refresh_tokens_seq increment by 50;

create table authors (
    id         bigint generated by default as identity primary key,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    name       varchar(255) not null,
    book_count integer default 0
);

create table categories (
    id         bigint generated by default as identity primary key,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    name       varchar(255) not null
);

create table books (
    id               bigint generated by default as identity primary key,
    created_at       timestamp(6) with time zone not null,
    updated_at       timestamp(6) with time zone,
    cover_image_url  varchar(255),
    description      varchar(5000),
    isbn             varchar(255) not null unique,
    price            numeric(10, 2) not null,
    title            varchar(255) not null,
    category_id      bigint not null, -- FK to categories
    version          bigint default 0 not null,
    format           varchar(255),
    language         varchar(255),
    page_count       integer,
    published_date   date,
    publisher        varchar(255),
    available_copies integer
);

create table book_authors (
    book_id   bigint not null, -- FK to books
    author_id bigint not null, -- FK to authors
    primary key (book_id, author_id)
);

create table copies (
    id         bigint generated by default as identity primary key,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    barcode    varchar(255) not null unique,
    status     varchar(255) not null check ((status)::text = ANY ((ARRAY ['AVAILABLE', 'LOANED', 'MAINTENANCE', 'LOST', 'RETIRED'])::text[])),
    book_id    bigint not null, -- FK to books
    version    bigint default 0 not null,
    location   varchar(255)
);

create table users (
    id         bigint generated by default as identity primary key,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    email      varchar(255) not null unique,
    first_name varchar(50) not null,
    last_name  varchar(50) not null,
    password   varchar(128) not null,
    status     varchar(255) not null check ((status)::text = ANY ((ARRAY ['ACTIVE', 'INACTIVE', 'BANNED', 'DELETED'])::text[])),
    version    bigint default 0 not null
);

create table loans (
    id          bigint generated by default as identity primary key,
    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone,
    due_date    timestamp(6) with time zone not null,
    loan_date   timestamp(6) with time zone not null,
    return_date timestamp(6) with time zone,
    status      varchar(255) not null check ((status)::text = ANY ((ARRAY ['ACTIVE', 'OVERDUE', 'RETURNED', 'RETURNED_OVERDUE', 'RETURNED_DAMAGED', 'LOST'])::text[])),
    copy_id     bigint not null, -- FK to copies
    user_id     bigint not null, -- FK to users
    version     bigint not null
);

create table fines (
    id           bigint generated by default as identity primary key,
    created_at   timestamp(6) with time zone not null,
    updated_at   timestamp(6) with time zone,
    amount       numeric(10, 2) not null,
    fine_date    timestamp(6) with time zone not null,
    payment_date timestamp(6) with time zone,
    reason       varchar(255) not null,
    status       smallint not null check ((status >= 0) AND (status <= 2)),
    loan_id      bigint, -- FK to loans
    user_id      bigint not null, -- FK to users
    version      bigint not null
);

create table refresh_tokens (
    id          bigint not null primary key,
    expiry_date timestamp(6) with time zone not null,
    token       varchar(255) not null unique,
    user_id     bigint not null, -- FK to users
    updated_at  timestamp(6) with time zone
);

create table roles (
    name varchar(255) primary key
);

create table user_roles (
    user_id bigint not null, -- FK to users
    role    varchar(255) not null, -- FK to roles
    primary key (user_id, role)
);

create table user_notification_preferences (
    id         bigint generated by default as identity primary key,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    category   varchar(255) not null check ((category)::text = ANY ((ARRAY ['LOAN_OVERDUE', 'LOAN_DUE_SOON', 'FINE_ISSUED', 'FINE_PAID', 'GENERAL_ANNOUNCEMENT'])::text[])),
    user_id    bigint not null, -- FK to users
    unique (user_id, category)
);

create table user_notification_preference_channels (
    preference_id bigint not null, -- FK to user_notification_preferences
    channel       varchar(255) check ((channel)::text = ANY ((ARRAY ['EMAIL', 'SMS', 'PUSH_NOTIFICATION'])::text[]))
);
